#!/bin/bash

set -e 

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

set -x
ve/bin/isort trackers
ve/bin/black trackers --quiet
ve/bin/flake8 trackers
