# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trackers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trackers.proto',
  package='trackers',
  syntax='proto2',
  serialized_pb=_b('\n\x0etrackers.proto\x12\x08trackers\"7\n\x08Position\x12\x0b\n\x03lat\x18\x01 \x02(\x12\x12\x0b\n\x03lng\x18\x02 \x02(\x12\x12\x11\n\televation\x18\x03 \x01(\x03\"\xe2\x02\n\x05Point\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0c\n\x04time\x18\x02 \x01(\x04\x12\x16\n\x0etime_from_last\x18\x03 \x01(\x03\x12\x13\n\x0bserver_time\x18\x04 \x01(\x04\x12\x1d\n\x15server_time_from_last\x18\x05 \x01(\x03\x12$\n\x08position\x18\x06 \x01(\x0b\x32\x12.trackers.Position\x12\x17\n\x0froute_elevation\x18\x07 \x01(\x03\x12\x10\n\x08track_id\x18\x08 \x01(\r\x12\x0c\n\x04\x64ist\x18\t \x01(\x04\x12\x12\n\ndist_route\x18\n \x01(\x04\x12\x16\n\x0e\x64ist_from_last\x18\x0b \x01(\x04\x12\x0f\n\x07num_sat\x18\x0c \x01(\r\x12\x17\n\x0fspeed_from_last\x18\r \x01(\x02\x12\x0e\n\x06\x63onfig\x18\x0e \x01(\t\x12\x14\n\x0crider_status\x18\x0f \x01(\t\x12\x15\n\rfinished_time\x18\x10 \x01(\x04\")\n\x06Points\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.trackers.Point\"T\n\x13RouteElevationPoint\x12\x0b\n\x03lat\x18\x01 \x02(\x12\x12\x0b\n\x03lng\x18\x02 \x02(\x12\x12\x11\n\televation\x18\x03 \x02(\x03\x12\x10\n\x08\x64istance\x18\x04 \x02(\x04\"&\n\nRoutePoint\x12\x0b\n\x03lat\x18\x01 \x02(\x12\x12\x0b\n\x03lng\x18\x02 \x02(\x12\"\xb0\x01\n\x05Route\x12\x30\n\televation\x18\x01 \x03(\x0b\x32\x1d.trackers.RouteElevationPoint\x12$\n\x06points\x18\x02 \x03(\x0b\x32\x14.trackers.RoutePoint\x12\x0c\n\x04main\x18\x03 \x02(\x08\x12\x13\n\x0b\x64ist_factor\x18\x04 \x01(\x02\x12\x16\n\x0estart_distance\x18\x05 \x01(\x02\x12\x14\n\x0c\x65nd_distance\x18\x06 \x01(\x02\")\n\x06Routes\x12\x1f\n\x06routes\x18\x01 \x03(\x0b\x32\x0f.trackers.Route')
)




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='trackers.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='trackers.Position.lat', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='trackers.Position.lng', index=1,
      number=2, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='trackers.Position.elevation', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=83,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='trackers.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='trackers.Point.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='trackers.Point.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_from_last', full_name='trackers.Point.time_from_last', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_time', full_name='trackers.Point.server_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_time_from_last', full_name='trackers.Point.server_time_from_last', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='trackers.Point.position', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='route_elevation', full_name='trackers.Point.route_elevation', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='trackers.Point.track_id', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist', full_name='trackers.Point.dist', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_route', full_name='trackers.Point.dist_route', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_from_last', full_name='trackers.Point.dist_from_last', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_sat', full_name='trackers.Point.num_sat', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_from_last', full_name='trackers.Point.speed_from_last', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='trackers.Point.config', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rider_status', full_name='trackers.Point.rider_status', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finished_time', full_name='trackers.Point.finished_time', index=15,
      number=16, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=440,
)


_POINTS = _descriptor.Descriptor(
  name='Points',
  full_name='trackers.Points',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='trackers.Points.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=483,
)


_ROUTEELEVATIONPOINT = _descriptor.Descriptor(
  name='RouteElevationPoint',
  full_name='trackers.RouteElevationPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='trackers.RouteElevationPoint.lat', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='trackers.RouteElevationPoint.lng', index=1,
      number=2, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='trackers.RouteElevationPoint.elevation', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='trackers.RouteElevationPoint.distance', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=569,
)


_ROUTEPOINT = _descriptor.Descriptor(
  name='RoutePoint',
  full_name='trackers.RoutePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='trackers.RoutePoint.lat', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='trackers.RoutePoint.lng', index=1,
      number=2, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=609,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='trackers.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elevation', full_name='trackers.Route.elevation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='trackers.Route.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='main', full_name='trackers.Route.main', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_factor', full_name='trackers.Route.dist_factor', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_distance', full_name='trackers.Route.start_distance', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_distance', full_name='trackers.Route.end_distance', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=788,
)


_ROUTES = _descriptor.Descriptor(
  name='Routes',
  full_name='trackers.Routes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='trackers.Routes.routes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=790,
  serialized_end=831,
)

_POINT.fields_by_name['position'].message_type = _POSITION
_POINTS.fields_by_name['points'].message_type = _POINT
_ROUTE.fields_by_name['elevation'].message_type = _ROUTEELEVATIONPOINT
_ROUTE.fields_by_name['points'].message_type = _ROUTEPOINT
_ROUTES.fields_by_name['routes'].message_type = _ROUTE
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Points'] = _POINTS
DESCRIPTOR.message_types_by_name['RouteElevationPoint'] = _ROUTEELEVATIONPOINT
DESCRIPTOR.message_types_by_name['RoutePoint'] = _ROUTEPOINT
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['Routes'] = _ROUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.Position)
  ))
_sym_db.RegisterMessage(Position)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.Point)
  ))
_sym_db.RegisterMessage(Point)

Points = _reflection.GeneratedProtocolMessageType('Points', (_message.Message,), dict(
  DESCRIPTOR = _POINTS,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.Points)
  ))
_sym_db.RegisterMessage(Points)

RouteElevationPoint = _reflection.GeneratedProtocolMessageType('RouteElevationPoint', (_message.Message,), dict(
  DESCRIPTOR = _ROUTEELEVATIONPOINT,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.RouteElevationPoint)
  ))
_sym_db.RegisterMessage(RouteElevationPoint)

RoutePoint = _reflection.GeneratedProtocolMessageType('RoutePoint', (_message.Message,), dict(
  DESCRIPTOR = _ROUTEPOINT,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.RoutePoint)
  ))
_sym_db.RegisterMessage(RoutePoint)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.Route)
  ))
_sym_db.RegisterMessage(Route)

Routes = _reflection.GeneratedProtocolMessageType('Routes', (_message.Message,), dict(
  DESCRIPTOR = _ROUTES,
  __module__ = 'trackers_pb2'
  # @@protoc_insertion_point(class_scope:trackers.Routes)
  ))
_sym_db.RegisterMessage(Routes)


# @@protoc_insertion_point(module_scope)
